title: Ezgi Soylu # your name (or website title) here
logo: "/IMG_9646.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  It;s almost christmas 
  I want some pizza  <br><br>
  <a href="https://www.linkedin.com/in/ezgisoylu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
